//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drg.TestMeteoDriver.MeteoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MeteoServiceReference.IMeteoService")]
    public interface IMeteoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeteoService/FixMeteoData", ReplyAction="http://tempuri.org/IMeteoService/FixMeteoDataResponse")]
        void FixMeteoData(Drg.CommonData.MeteoData meteoData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeteoServiceChannel : Drg.TestMeteoDriver.MeteoServiceReference.IMeteoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeteoServiceClient : System.ServiceModel.ClientBase<Drg.TestMeteoDriver.MeteoServiceReference.IMeteoService>, Drg.TestMeteoDriver.MeteoServiceReference.IMeteoService {
        
        public MeteoServiceClient() {
        }
        
        public MeteoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeteoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeteoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeteoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void FixMeteoData(Drg.CommonData.MeteoData meteoData) {
            base.Channel.FixMeteoData(meteoData);
        }
    }
}
